apiVersion: v1
kind: Pod
metadata:
  name: nats-box
spec:
  containers:
    - name: nats-box
      image: natsio/nats-box:latest
      command:
        - sh
        - -ec
        - trap true INT TERM; sleep infinity & wait
      # resources:
      #   requests:
      #     cpu: 100m
      #     memory: 128Mi
      #   limits:
      #     cpu: 250m
      #     memory: 256Mi
      volumeMounts:
        - mountPath: "/data"
          name: nats-tools-data
          readOnly: false
  volumes:
    - name: nats-tools-data
      persistentVolumeClaim:
        claimName: nats-tools-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-tools-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 1Gi

